// <auto-generated />
using System;
using BankApp.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankApp.Core.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20181225171943_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankApp.Core.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CurrentSum");

                    b.Property<string>("Name");

                    b.Property<int>("Percentage");

                    b.Property<int?>("TypeAccountTypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeAccountTypeId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankApp.Core.Models.AccountType", b =>
                {
                    b.Property<int>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("AccountTypeId");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("BankApp.Core.Models.Account", b =>
                {
                    b.HasOne("BankApp.Core.Models.AccountType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeAccountTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
